//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int Id { get; set; }
        public string Desc { get; set; }
        public string Photo { get; set; }
        public string Signature { get; set; }
        public string Vision { get; set; }
        public string History { get; set; }
    }
}
