//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> CatigoryId { get; set; }
        public string Photo { get; set; }
        public string Texts { get; set; }
        public string Tags { get; set; }
    
        public virtual BlogCat BlogCat { get; set; }
    }
}
